version: '3'

services:  
  postgresql:
    image: 'bitnami/postgresql:latest'
    container_name: airflow_db
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    volumes:
      - airflow-postgresql-volume:/bitnami/postgresql

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - airflow-redis-volume:/bitnami

  airflow-scheduler:
    #image: bitnami/airflow-scheduler:latest
    build:
      context: .
      dockerfile: airflow-scheduler/Dockerfile
    restart: always
    container_name: scheduler
    environment:
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./db_backups:/opt/bitnami/airflow/db_backups

  airflow-worker:
    #image: bitnami/airflow-worker:latest
    build: 
      context: .
      dockerfile: airflow-worker/Dockerfile
    container_name: worker
    environment:
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./db_backups:/opt/bitnami/airflow/db_backups

  airflow:
    #image: bitnami/airflow:latest
    build: 
      context: .
      dockerfile: airflow/Dockerfile
    container_name: webserver
    environment:
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Africa/Nairobi
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_EXPOSE_CONFIG=True
    ports:
      - '8080:8080'
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./db_backups:/opt/bitnami/airflow/db_backups

volumes:
  airflow-postgresql-volume: {}
  airflow-redis-volume: {}